### ISSUE TITLE
Remove network dependencies?

### ISSUE THREAD

**Issue by afcowie** [valderman/shellmate#4]
Would it be possible to split this package into two pieces? I fully respect how much extra work that implies, but dragging dependencies like **HTTP** and **tagsoup** and libcurl (!) into a project that has nothing to do with downloading files [or, if it did, will quite properly use **http-conduit** or **http-streams** in the main program] makes for a lot of additional dependency burden, and really makes **shellmate** unattractive if writing simple wrapper scripts around process execution.

Maybe **shellmate** and **shellmate-downloader** or something.

Anyway, I realize this sounds like a whinge, but keeping the surface area limited makes it easier to avoid conflicts when considering whether to use a library as a dependency.

AfC

**Comment by valderman** [comment]
This absolutely makes sense and is not a lot of extra work. This was the plan from the start, but somehow got lost on the way. I'll fix this before the next release.

**Comment by valderman** [comment]
In the meantime, you can work around the most egregious dependency bloat by passing `-f-download-extras` to cabal when installing. You'll still get `HTTP` and `network-uri`, but at least you'll avoid the feed stuff.

**Comment by afcowie** [comment]
@valderman that's all right. I'll wait until you have a chance to work this out properly.

**Comment by afcowie** [comment]
(Nice!)
